version: "3.8"

services:
  laravel:
    image: rzaynuri/laravel-app:2
    ports:
      - "8081:80"  # Ganti dengan port yang tidak digunakan, misalnya 8081
    networks:
      - laravel_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  laravel_net:
    driver: overlay
