apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app
        image: rzaynuri/laravel-app:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: laravel-env
        - secretRef:
            name: laravel-secret
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: LoadBalancer   # pakai LoadBalancer agar bisa dapat external IP dari MetalLB
  selector:
    app: laravel-app
  ports:
    - port: 80
      targetPort: 80
