version: "3.8"

services:
  laravel:
    image: rzaynuri/laravel-app:latest
    ports:
      - "80:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: overlay
